const userStateIds = {
    FEEDBACK_AWAITING: 'FEEDBACK_AWAITING', 
    TESTIMONY_AWAITING: 'TESTIMONY_AWAITING', 
    MANAGE_AWAITING_ANNOUNCEMENT: 'MANAGE_AWAITING_ANNOUNCEMENT',
    MANAGE_CONFIRMING_ANNOUNCEMENT: 'MANAGE_CONFIRMING_ANNOUNCEMENT',
    MANAGE_AWAITING_LIVESTREAM: 'MANAGE_AWAITING_LIVESTREAM',
    MANAGE_CONFIRMING_LIVESTREAM: 'MANAGE_CONFIRMING_LIVESTREAM',
    MANAGE_APPROVING_TESTIMONIES: 'MANAGE_APPROVING_TESTIMONIES',
    MANAGE_CHOOSING_TESTIMONIES: 'MANAGE_CHOOSING_TESTIMONIES'
}

module.exports = userStateIds;