const [FEEDBACK_AWAITING, TESTIMONY_AWAITING, ANNOUNCEMENT_AWAITING, ANNOUNCEMENT_CONFIRMING] = ['FEEDBACK_AWAITING', 'TESTIMONY_AWAITING', 'ANNOUNCEMENT_AWAITING', 'ANNOUNCEMENT_CONFIRMING'];

module.exports = {
    FEEDBACK_AWAITING, 
    TESTIMONY_AWAITING, 
    ANNOUNCEMENT_AWAITING, 
    ANNOUNCEMENT_CONFIRMING
}